### ISSUE TITLE
WebView 在下拉加载更多的时候 ，会出现崩溃，抽屉栏最下面的标签无法点击

### ISSUE THREAD

**Issue by yimouleng** [zpz1237/NirZhihuDaily2.0#2]
WebView 在下拉加载更多的时候 ，会出现崩溃，抽屉栏最下面的标签无法点击。

webview加载位置，可能超出范围。

抽屉标签无法点击可能scrollView的contentOffset设置有问题

![3016934e-6a21-4aae-8e30-07c84dc523ea](https://cloud.githubusercontent.com/assets/8896046/10841339/63727170-7f23-11e5-90ab-7d79d4bb1fa7.png)

**Comment by zpz1237** [comment]
抽屉栏最下面和最上面没法点击是因为我没做，那个是图片不是button，Webview上拉加载更多崩溃是偶发的还是必然的？
