### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by ZsIsMe** [zpz1237/NirZhihuDaily2.0#3]
1. 进入详情页奔溃的问题：
   这个不太好重现，而且同一个点击两次不一定出现问题：
   ![2015-11-08 4 38 49](https://cloud.githubusercontent.com/assets/7468754/11019542/9e012842-8638-11e5-84ea-f0027a962668.png)
   在WebViewController.swift
   估计是有些可选类型你强制置“!”但事实上没数值崩溃了，很难重现，有更详细的信息我会补充。
2.  其实叶不算bug，但感觉怪怪的：

![default](https://cloud.githubusercontent.com/assets/7468754/11019553/4bd0bf64-8639-11e5-8717-2970ae3570ea.gif)
我觉得侧滑栏出现的时候utableview的cell不能点击，而tableview本身接受到点🐔事件要收起侧边栏，你认为呢？

**Comment by zpz1237** [comment]
我会尽快修改

**Comment by zpz1237** [comment]
两个问题均已解决 感谢反馈
